Rename to SpringFlow

diff --git a/git-sf-feature b/git-sf-feature
--- a/git-sf-feature
+++ b/git-sf-feature
@@ -41,22 +41,22 @@
 #
 
 require_git_repo
-require_hubflow_initialized
-hubflow_load_settings
-PREFIX=$(git config --get hubflow.prefix.feature)
+require_springflow_initialized
+springflow_load_settings
+PREFIX=$(git config --get springflow.prefix.feature)
 
 usage() {
-	echo "usage: git hf feature [list] [-v]"
-	echo "       git hf feature start <name> [<base>]"
-	echo "       git hf feature submit [<name>] [<base>]"
-	echo "       git hf feature finish [-rFkD] [<name|nameprefix>]"
-	echo "       git hf feature track <name>"
-	echo "       git hf feature diff [<name|nameprefix>]"
-	echo "       git hf feature rebase [-i] [<name|nameprefix>]"
-	echo "       git hf feature checkout [<name|nameprefix>]"
-	echo "       git hf feature pull [-r] [<remote> [<name>]]"
-	echo "       git hf feature push [<remote> [<name>]]"
-	echo "       git hf feature cancel [-f] <name>"
+	echo "usage: git sf feature [list] [-v]"
+	echo "       git sf feature start <name> [<base>]"
+	echo "       git sf feature submit [<name>] [<base>]"
+	echo "       git sf feature finish [-rFkD] [<name|nameprefix>]"
+	echo "       git sf feature track <name>"
+	echo "       git sf feature diff [<name|nameprefix>]"
+	echo "       git sf feature rebase [-i] [<name|nameprefix>]"
+	echo "       git sf feature checkout [<name|nameprefix>]"
+	echo "       git sf feature pull [-r] [<remote> [<name>]]"
+	echo "       git sf feature push [<remote> [<name>]]"
+	echo "       git sf feature cancel [-f] <name>"
 }
 
 cmd_default() {
@@ -76,7 +76,7 @@ cmd_list() {
 		warn ""
 		warn "You can start a new feature branch:"
 		warn ""
-		warn "    git hf feature start <name> [<base>]"
+		warn "    git sf feature start <name> [<base>]"
 		warn ""
 		exit 0
 	fi
@@ -139,8 +139,8 @@ expand_nameprefix_arg() {
 
 	local expanded_name
 	local exitcode
-    track_repo=$(hubflow_track_repo "$NAME" "$PREFIX" "$ORIGIN")	
-    expanded_name=$(hubflow_resolve_nameprefix "$NAME" "$PREFIX")
+    track_repo=$(springflow_track_repo "$NAME" "$PREFIX" "$ORIGIN")	
+    expanded_name=$(springflow_resolve_nameprefix "$NAME" "$PREFIX")
 	exitcode=$?
 	case $exitcode in
 		0) NAME=$expanded_name
@@ -208,7 +208,7 @@ cmd_start() {
 	require_clean_working_tree
 	require_remote_available
 	if flag fetch ; then
-		hubflow_fetch_latest_changes_from_origin
+		springflow_fetch_latest_changes_from_origin
 	fi
 	require_branch_absent "$ORIGIN/$BRANCH"
 
@@ -224,7 +224,7 @@ cmd_start() {
 	fi
 
 	# push it back up to remote repo
-	hubflow_push_latest_changes_to_origin
+	springflow_push_latest_changes_to_origin
 
 	echo
 	echo "Summary of actions:"
@@ -235,7 +235,7 @@ cmd_start() {
 	echo "Now, start committing on your feature. When done, create a"
 	echo "pull request on GitHub.  Once that has been merged, use:"
 	echo ""
-	echo "     git hf feature finish $NAME"
+	echo "     git sf feature finish $NAME"
 	echo
 }
 
@@ -249,10 +249,10 @@ cmd_submit() {
 	require_clean_working_tree
     require_github_origin_repo
 	require_remote_available
-	hubflow_fetch_latest_changes_from_origin
+	springflow_fetch_latest_changes_from_origin
 
 	# push to origin
-	hubflow_push_latest_changes_to_origin
+	springflow_push_latest_changes_to_origin
 
 	# pull request details
 	PR_FILE="./COMMIT_MSG"
@@ -328,7 +328,7 @@ EOS
 	echo ""
 	echo "Once the Pull Request has been accepted, cleanup the feature with:"
 	echo ""
-	echo "     git hf feature finish $NAME"
+	echo "     git sf feature finish $NAME"
 	echo
 }
 
@@ -349,7 +349,7 @@ cmd_finish() {
 	# update local repo with remote changes first, if asked
 	if flag fetch; then
 		# fetch and merge the latest changes from origin
-		hubflow_merge_latest_changes_from_origin
+		springflow_merge_latest_changes_from_origin
 	fi
 
 	if has "$ORIGIN/$BRANCH" $(git_remote_branches); then
@@ -371,11 +371,11 @@ cmd_finish() {
 
 	# if the user wants to rebase, do that first
 	if flag rebase; then
-		if ! git hf feature rebase "$NAME" "$DEVELOP_BRANCH"; then
+		if ! git sf feature rebase "$NAME" "$DEVELOP_BRANCH"; then
 			warn "Finish was aborted due to conflicts during rebase."
 			warn "Please finish the rebase manually now."
 			warn "When finished, re-run:"
-			warn "    git hf feature finish '$NAME' '$DEVELOP_BRANCH'"
+			warn "    git sf feature finish '$NAME' '$DEVELOP_BRANCH'"
 			exit 1
 		fi
 	fi
@@ -383,7 +383,7 @@ cmd_finish() {
 	# merge into the develop branch
 	# the merge_helper will not return if there is a merge conflict
 	# we want to remain on the DEVELOP_BRANCH after the merge is complete
-	hubflow_local_merge_helper "$BRANCH" "$DEVELOP_BRANCH" no_checkout_afterwards
+	springflow_local_merge_helper "$BRANCH" "$DEVELOP_BRANCH" no_checkout_afterwards
 
 	# make sure the merge worked
 	if [[ $(git rev-list -n2 "$DEVELOP_BRANCH..$BRANCH") ]] ; then
@@ -397,10 +397,10 @@ cmd_finish() {
 	fi
 
 	# switch to the develop branch
-	hubflow_change_branch "$DEVELOP_BRANCH"
+	springflow_change_branch "$DEVELOP_BRANCH"
 
 	# if we merged locally, push those changes up to origin
-	hubflow_push_latest_changes_to_origin
+	springflow_push_latest_changes_to_origin
 
 	# delete the local branch if it is no longer needed
 	if noflag keep; then
@@ -481,18 +481,18 @@ avoid_accidental_cross_branch_action() {
 	local current_branch=$(git_current_branch)
 	if [ "$BRANCH" != "$current_branch" ]; then
 		warn "Trying to pull from '$BRANCH' while currently on branch '$current_branch'."
-		warn "To avoid unintended merges, hubflow aborted."
+		warn "To avoid unintended merges, springflow aborted."
 		return 1
 	fi
 	return 0
 }
 
 cmd_pull() {
-	git hf pull "$@"
+	git sf pull "$@"
 }
 
 cmd_push() {
-	git hf push "$@"
+	git sf push "$@"
 }
 
 cmd_cancel() {
diff --git a/git-sf-pull b/git-sf-pull
--- a/git-sf-pull
+++ b/git-sf-pull
@@ -41,19 +41,55 @@
 # policies, either expressed or implied, of Vincent Driessen.
 #
 
+require_git_repo
+require_springflow_initialized
+springflow_load_settings
+
 usage() {
-	echo "usage: git hf version"
+    echo "usage: git sf pull [-r]"
+}
+
+parse_args() {
+    # parse options
+    FLAGS "$@" || exit $?
+    eval set -- "${FLAGS_ARGV}"
 }
 
 cmd_default() {
-	if hubflow_has_new_version_available > /dev/null ; then
-		echo "$HUBFLOW_VERSION - upgrade available"
-	else
-		echo "$HUBFLOW_VERSION - latest version"
-	fi
+    cmd_pull "$@"
 }
 
 cmd_help() {
-	usage
-	exit 0
+    usage
+    exit 0
+}
+
+cmd_pull() {
+    # we support rebasing
+    DEFINE_boolean rebase false "pull with rebase" r
+    parse_args "$@"
+
+    # make sure we're okay to start
+    require_clean_working_tree
+
+    # we need to fetch the latest changes from upstream, before we can merge
+    springflow_fetch_latest_changes_from_origin
+
+    # merge the changes from upstream
+    if flag rebase ; then
+        git pull --rebase "$ORIGIN"
+        if [[ $? -ne 0 ]]; then
+            warn "Pull was aborted."
+            warn
+            warn "There might be conflicts during the rebase, or '$ORIGIN' may be inaccessible."
+            exit 1
+        fi
+    else
+        springflow_remote_merge_helper "$ORIGIN" "$BRANCH"
+    fi
+
+    # all done
+    echo
+    echo "Summary of actions:"
+    echo "- Any changes from $ORIGIN/$BRANCH have been pulled into branch '$BRANCH'"
 }
diff --git a/git-sf-release b/git-sf-release
--- a/git-sf-release
+++ b/git-sf-release
@@ -14,6 +14,7 @@
 # Copyright 2010 Vincent Driessen. All rights reserved.
 # Copyright 2012 MediaSift Ltd. All rights reserved.
 #
+#
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
 #
@@ -41,19 +42,18 @@
 #
 
 require_git_repo
-require_hubflow_initialized
-hubflow_load_settings
-VERSION_PREFIX=$(eval "echo `git config --get hubflow.prefix.versiontag`")
-PREFIX=$(git config --get hubflow.prefix.hotfix)
+require_springflow_initialized
+springflow_load_settings
+VERSION_PREFIX=$(eval "echo `git config --get springflow.prefix.versiontag`")
+PREFIX=$(git config --get springflow.prefix.release)
 
 usage() {
-	echo "usage: git hf hotfix [list] [-v]"
-	echo "       git hf hotfix start <version> [<base>]"
-	echo "       git hf hotfix finish [-sumpk] <version>"
-	echo "       git hf hotfix track <name>"
-	echo "       git hf hotfix pull [-r] [<remote> [<version>]]"
-	echo "       git hf hotfix push [<remote> [<version>]]"
-	echo "       git hf hotfix cancel [-f] <version>"
+	echo "usage: git sf release [list] [-v]"
+	echo "       git sf release start <version> [<base>]"
+	echo "       git sf release finish [-sumpk] <version>"
+	echo "       git sf release cancel <version>"
+	echo "       git sf release push [<name>]"
+	echo "       git sf release pull [<name>]"
 }
 
 cmd_default() {
@@ -64,21 +64,22 @@ cmd_list() {
 	DEFINE_boolean verbose false 'verbose (more) output' v
 	parse_args "$@"
 
-	local hotfix_branches
+	local release_branches
 	local current_branch
 	local short_names
-	hotfix_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
-	if [ -z "$hotfix_branches" ]; then
-		warn "No hotfix branches exist."
+	release_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
+	if [ -z "$release_branches" ]; then
+		warn "No release branches exist."
                 warn ""
-                warn "You can start a new hotfix branch:"
+                warn "You can start a new release branch:"
                 warn ""
-                warn "    git hf hotfix start <version> [<base>]"
+                warn "    git sf release start <name> [<base>]"
                 warn ""
 		exit 0
 	fi
+
 	current_branch=$(git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g')
-	short_names=$(echo "$hotfix_branches" | sed "s ^$PREFIX  g")
+	short_names=$(echo "$release_branches" | sed "s ^$PREFIX  g")
 
 	# determine column width first
 	local width=0
@@ -92,8 +93,8 @@ cmd_list() {
 	local branch
 	for branch in $short_names; do
 		local fullname=$PREFIX$branch
-		local base=$(git merge-base "$fullname" "$MASTER_BRANCH")
-		local master_sha=$(git rev-parse "$MASTER_BRANCH")
+		local base=$(git merge-base "$fullname" "$DEVELOP_BRANCH")
+		local develop_sha=$(git rev-parse "$DEVELOP_BRANCH")
 		local branch_sha=$(git rev-parse "$fullname")
 		if [ "$fullname" = "$current_branch" ]; then
 			printf "* "
@@ -102,16 +103,10 @@ cmd_list() {
 		fi
 		if flag verbose; then
 			printf "%-${width}s" "$branch"
-			if [ "$branch_sha" = "$master_sha" ]; then
+			if [ "$branch_sha" = "$develop_sha" ]; then
 				printf "(no commits yet)"
 			else
-				local tagname=$(git name-rev --tags --no-undefined --name-only "$base")
-				local nicename
-				if [ "$tagname" != "" ]; then
-					nicename=$tagname
-				else
-					nicename=$(git rev-parse --short "$base")
-				fi
+				local nicename=$(git rev-parse --short "$base")
 				printf "(based on $nicename)"
 			fi
 		else
@@ -126,12 +121,6 @@ cmd_help() {
 	exit 0
 }
 
-name_or_current() {
-	if [ -z "$NAME" ]; then
-		use_current_hotfix_branch_name
-	fi
-}
-
 parse_args() {
 	# parse options
 	FLAGS "$@" || exit $?
@@ -142,78 +131,61 @@ parse_args() {
 	BRANCH=$PREFIX$VERSION
 }
 
-parse_remote_name() {
-	# parse options
-	FLAGS "$@" || exit $?
-	eval set -- "${FLAGS_ARGV}"
-
-	# read arguments into global variables
-	REMOTE=$1
-	NAME=$2
-	BRANCH=$PREFIX$VERSION
-}
-
 require_version_arg() {
-	if [ "$VERSION" == "" ]; then
+	if [ "$VERSION" = "" ]; then
 		warn "Missing argument <version>"
 		usage
 		exit 1
 	fi
 }
 
-require_base_is_on_master() {
+require_base_is_on_develop() {
 	if ! git branch --no-color --contains "$BASE" 2>/dev/null \
 			| sed 's/[* ] //g' \
-	  		| grep -q "^$MASTER_BRANCH\$"; then
-		die "fatal: Given base '$BASE' is not a valid commit on '$MASTER_BRANCH'."
+	  		| grep -q "^$DEVELOP_BRANCH\$"; then
+		die "fatal: Given base '$BASE' is not a valid commit on '$DEVELOP_BRANCH'."
 	fi
 }
 
-require_no_existing_hotfix_branches() {
-	local hotfix_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
-	local first_branch=$(echo ${hotfix_branches} | head -n1)
+require_no_existing_release_branches() {
+	local release_branches=$(echo "$(git_local_branches)" | grep "^$PREFIX")
+	local first_branch=$(echo ${release_branches} | head -n1)
 	first_branch=${first_branch#$PREFIX}
-	[ -z "$hotfix_branches" ] || \
-		die "There is an existing hotfix branch ($first_branch). Finish that one first."
-}
-
-use_current_hotfix_branch_name() {
-	local current_branch=$(git_current_branch)
-	if startswith "$current_branch" "$PREFIX"; then
-		BRANCH=$current_branch
-		NAME=${BRANCH#$PREFIX}
-	else
-		warn "The current HEAD is not a hotfix branch."
-		warn "Please specify a <name> argument."
-		exit 1
-	fi
+	[ -z "$release_branches" ] || \
+		die "There is an existing release branch ($first_branch). Finish that one first."
 }
 
 cmd_start() {
 	DEFINE_boolean fetch true "fetch from $ORIGIN before creating the new branch" F
 	parse_args "$@"
-	BASE=${2:-$MASTER_BRANCH}
+	BASE=${2:-$DEVELOP_BRANCH}
 	require_version_arg
 
 	# sanity checks
 	require_clean_working_tree
 	require_remote_available
 	if flag fetch ; then
-		hubflow_fetch_latest_changes_from_origin
+		springflow_fetch_latest_changes_from_origin
 	fi
-	require_base_is_on_master
-	require_no_existing_hotfix_branches
+	require_base_is_on_develop
+	require_no_existing_release_branches
+
+	# sanity checks
+	require_clean_working_tree
 	require_branch_absent "$BRANCH"
 	require_tag_absent "$VERSION_PREFIX$VERSION"
-	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
-		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
+	if noflag nofetch; then
+		git fetch -q "$ORIGIN" "$DEVELOP_BRANCH"
+	fi
+	if has "$ORIGIN/$DEVELOP_BRANCH" $(git_remote_branches); then
+		require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
 	fi
 
 	# create branch
 	git checkout -b "$BRANCH" "$BASE"
 
 	# push it back up to remote repo
-	hubflow_push_latest_changes_to_origin
+	springflow_push_latest_changes_to_origin
 
 	echo
 	echo "Summary of actions:"
@@ -223,10 +195,10 @@ cmd_start() {
 	echo
 	echo "Follow-up actions:"
 	echo "- Bump the version number now!"
-	echo "- Start committing your hot fixes"
+	echo "- Start committing last-minute fixes in preparing your release"
 	echo "- When done, run:"
 	echo
-	echo "     git hf hotfix finish '$VERSION'"
+	echo "     git sf release finish '$VERSION'"
 	echo
 }
 
@@ -238,7 +210,8 @@ cmd_finish() {
 	DEFINE_boolean push true "push to $ORIGIN after performing finish" p
 	DEFINE_boolean keep false "keep branch after performing finish" k
 	DEFINE_boolean notag false "don't tag this release" n
-	DEFINE_boolean nobackmerge false "don't back-merge $MASTER_BRANCH to be a parent of $DEVELOP_BRANCH (using tag if applicable)" b	parse_args "$@"
+	DEFINE_boolean nobackmerge false "don't back-merge $MASTER_BRANCH to be a parent of $DEVELOP_BRANCH (using tag if applicable)" b
+
 	parse_args "$@"
 	require_version_arg
 
@@ -251,14 +224,22 @@ cmd_finish() {
 	require_branch "$BRANCH"
 	require_clean_working_tree
 	require_remote_available
+	if flag fetch ; then
+		springflow_fetch_latest_changes_from_origin
+	fi
 
 	# update local repo with remote changes first, if asked
 	if flag fetch; then
 		# fetch and merge the latest changes from origin
-		hubflow_merge_latest_changes_from_origin
+		springflow_merge_latest_changes_from_origin
 	fi
 
-	# we must be up to date before continuing
+	# push up to origin
+	if flag push ; then
+		springflow_push_latest_changes_to_origin
+	fi
+
+	# we need to be up to date before we go any further
 	if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
 		require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
 	fi
@@ -287,14 +268,14 @@ cmd_finish() {
 			flag sign && opts="$opts -s"
 			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
 			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
-			eval git tag $opts "$VERSION_PREFIX$VERSION" || \
+			eval git tag $opts "$tagname" || \
 			die "Tagging failed. Please run finish again to retry."
 		fi
 	fi
 
 	# try to merge into develop
 	if noflag nobackmerge; then
-		# in case a previous attempt to finish this hotfix branch has failed,
+		# in case a previous attempt to finish this release branch has failed,
 		# but the merge into develop was successful, we skip it now
 		if ! git_is_branch_merged_into "$MASTER_BRANCH" "$DEVELOP_BRANCH"; then
 			git checkout "$DEVELOP_BRANCH" || \
@@ -307,30 +288,26 @@ cmd_finish() {
 					die "There were merge conflicts."
 			else
 				git merge --no-ff "$MASTER_BRANCH" || \
-					die "There were merge conflicts."
+				die "There were merge conflicts."
 			fi
 		fi
 	else
-		# in case a previous attempt to finish this hotfix branch has failed,
-		# but the merge into develop was successful, we skip it now
-		if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
-			git checkout "$DEVELOP_BRANCH" || \
-				die "Could not check out $DEVELOP_BRANCH."
-			# just merge the release branch into the development branch
-			git merge --no-ff "$BRANCH" || \
-				die "There were merge conflicts."
+	# in case a previous attempt to finish this release branch has failed,
+	# but the merge into develop was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "$DEVELOP_BRANCH"; then
+		git checkout "$DEVELOP_BRANCH" || \
+			die "Could not check out $DEVELOP_BRANCH."
+		# just merge the release branch into the development branch
+		git merge --no-ff "$BRANCH" || \
+			die "There were merge conflicts."
 		fi
 	fi
 
 	# delete branch
 	if noflag keep; then
-		# delete the remote branch first
-		if flag push ; then
-			git push "$ORIGIN" :"$BRANCH" || \
-				die "Could not delete remote branch"
+		if [ "$BRANCH" = "$(git_current_branch)" ]; then
+			git checkout "$MASTER_BRANCH"
 		fi
-
-		# delete the local branch afterwards
 		git branch -d "$BRANCH"
 	fi
 
@@ -341,25 +318,41 @@ cmd_finish() {
 			die "Could not push to $MASTER_BRANCH from $ORIGIN."
 		if noflag notag; then
 			git push --tags "$ORIGIN" || \
-				die "Could not push tags to $ORIGIN."
+			  die "Could not push tags to $ORIGIN."
+		fi
+		if noflag keep ; then
+			git push "$ORIGIN" :"$BRANCH" || \
+				die "Could not delete the remote $BRANCH in $ORIGIN."
 		fi
 	fi
 
 	echo
 	echo "Summary of actions:"
-	echo "- Latest objects have been fetched from '$ORIGIN'"
-	echo "- Hotfix branch has been merged into '$MASTER_BRANCH'"
-	if noflag notag; then
-		echo "- The hotfix was tagged '$VERSION_PREFIX$VERSION'"
+	if flag push ; then
+		echo "- Latest objects have been fetched from '$ORIGIN'"
 	fi
-	echo "- Hotfix branch has been back-merged into '$DEVELOP_BRANCH'"
-	if flag keep; then
-		echo "- Hotfix branch '$BRANCH' is still available"
+	echo "- Release branch has been merged into '$MASTER_BRANCH'"
+	if noflag notag; then
+		echo "- The release was tagged '$tagname'"
+		if noflag nobackmerge; then
+			echo "- Tag '$tagname' has been back-merged into '$DEVELOP_BRANCH'"
+		fi
+	fi
+	if flag nobackmerge; then
+		echo "- Release branch has been merged into '$DEVELOP_BRANCH'"
 	else
-		echo "- Hotfix branch '$BRANCH' has been deleted"
+		echo "- Branch '$MASTER_BRANCH' has been back-merged into '$DEVELOP_BRANCH'"
+	fi
+	if flag keep; then
+		echo "- Release branch '$BRANCH' is still available"
+	else
+		echo "- Release branch '$BRANCH' has been deleted"
 	fi
 	if flag push; then
 		echo "- '$DEVELOP_BRANCH', '$MASTER_BRANCH' and tags have been pushed to '$ORIGIN'"
+		if noflag keep ; then
+			echo "- Release branch '$BRANCH' in '$ORIGIN' has been deleted."
+		fi
 	fi
 	echo
 }
@@ -369,15 +362,15 @@ cmd_cancel() {
 	DEFINE_string message "" "use the given tag message" m
 	DEFINE_boolean push true "push to $ORIGIN after performing cancel" p
 	DEFINE_boolean keep false "keep branch after performing cancel" k
-	DEFINE_boolean force false "safety feature; cannot cancel a hotfix without this flag" f
-	DEFINE_boolean discard true "drop the changes in this hotfix; do not merge back into develop" d
+	DEFINE_boolean force false "safety feature; cannot cancel a release without this flag" f
+	DEFINE_boolean discard true "drop the changes in this release; do not merge back into develop" d
 
 	parse_args "$@"
 	require_version_arg
 
 	# has the user chosen the force flag?
 	if noflag force ; then
-		warn "To prevent you accidentally cancelling a hotfix, you _must_ use the -f flag"
+		warn "To prevent you accidentally cancelling a release, you _must_ use the -f flag"
 		warn "with this command"
 		exit 1
 	fi
@@ -386,7 +379,7 @@ cmd_cancel() {
 	require_branch "$BRANCH"
 	require_clean_working_tree
 	if flag push ; then
-		git push "$ORIGIN" "$BRANCH" || die "Could not push hotfix branch up to $ORIGIN"
+		git push "$ORIGIN" "$BRANCH" || die "Could not push release branch up to $ORIGIN"
 	fi
 
 	# we only merge into develop if the user hasn't selected the -d flag
@@ -410,7 +403,24 @@ cmd_cancel() {
 			git merge --no-ff "$BRANCH" || \
 				die "There were merge conflicts."
 		fi
+	fi
 
+	# delete branch
+	if noflag keep ; then
+		if [ "$BRANCH" = "$(git_current_branch)" ]; then
+			git checkout "$DEVELOP_BRANCH"
+		fi
+
+		# do we need to delete remote branch too?
+		if flag push ; then
+			git push "$ORIGIN" :"$BRANCH" || \
+				die "Could not delete the remote $BRANCH in $ORIGIN."
+		fi
+
+		git branch -d "$BRANCH"
+	fi
+
+	if noflag discard ; then
 		# push back to remote repo
 		if flag push ; then
 			git push "$ORIGIN" "$DEVELOP_BRANCH" || \
@@ -418,48 +428,101 @@ cmd_cancel() {
 		fi
 	fi
 
-	# delete the remote branch
-	if flag push ; then
-		git push "$ORIGIN" :"$BRANCH" || \
-			die "Could not delete the remote $BRANCH in $ORIGIN."
-	fi
-
-	# delete local branch
-	if noflag keep ; then
-		if [ "$BRANCH" = "$(git_current_branch)" ]; then
-			git checkout "$DEVELOP_BRANCH"
-		fi
-
-		git branch -D "$BRANCH"
-	fi
-
 	echo
 	echo "Summary of actions:"
 	if flag push ; then
 		echo "- Latest objects have been fetched from '$ORIGIN'"
 	fi
-	if noflag discard ; then
-		echo "- Hotfix branch has been merged into '$DEVELOP_BRANCH'"
-	fi
-	if noflag discard && flag push ; then
-		echo "- '$DEVELOP_BRANCH' has been pushed to '$ORIGIN'"
-	fi
-	if flag push ; then
-		echo "- Hotfix branch '$BRANCH' in '$ORIGIN' has been deleted."
+	if noflag nodiscard ; then
+		echo "- Release branch has been merged into '$DEVELOP_BRANCH'"
 	fi
 	if flag keep ; then
-		echo "- Hotfix branch '$BRANCH' is still available locally"
+		echo "- Release branch '$BRANCH' is still available"
 	else
-		echo "- Hotfix branch '$BRANCH' has been deleted locally"
+		echo "- Release branch '$BRANCH' has been deleted"
+		if flag push ; then
+			echo "- Release branch '$BRANCH' in '$ORIGIN' has been deleted."
+		fi
 	fi
 
+	if noflag nodiscard && flag push ; then
+		echo "- '$DEVELOP_BRANCH' has been pushed to '$ORIGIN'"
+	fi
+	echo
+}
+
+cmd_publish() {
+	parse_args "$@"
+	require_version_arg
+
+	# sanity checks
+	require_clean_working_tree
+	require_branch "$BRANCH"
+	git fetch -q "$ORIGIN"
+	require_branch_absent "$ORIGIN/$BRANCH"
+
+	# create remote branch
+	git push "$ORIGIN" "$BRANCH:refs/heads/$BRANCH"
+	git fetch -q "$ORIGIN"
+
+	# configure remote tracking
+	git config "branch.$BRANCH.remote" "$ORIGIN"
+	git config "branch.$BRANCH.merge" "refs/heads/$BRANCH"
+	git checkout "$BRANCH"
+
+	echo
+	echo "Summary of actions:"
+	echo "- A new remote branch '$BRANCH' was created"
+	echo "- The local branch '$BRANCH' was configured to track the remote branch"
+	echo "- You are now on branch '$BRANCH'"
 	echo
 }
 
 cmd_pull() {
-	git hf pull "$@"
+	git sf pull "$@"
 }
 
 cmd_push() {
-	git hf push "$@"
+	git sf push "$@"
+}
+
+
+parse_remote_name() {
+	# parse options
+	FLAGS "$@" || exit $?
+	eval set -- "${FLAGS_ARGV}"
+
+	# read arguments into global variables
+	REMOTE=$1
+	NAME=$2
+	BRANCH=$PREFIX$NAME
+}
+
+name_or_current() {
+	if [ -z "$NAME" ]; then
+		use_current_release_branch_name
+	fi
+}
+
+avoid_accidental_cross_branch_action() {
+	local current_branch=$(git_current_branch)
+	if [ "$BRANCH" != "$current_branch" ]; then
+		warn "Trying to pull from '$BRANCH' while currently on branch '$current_branch'."
+		warn "To avoid unintended merges, springflow aborted."
+		return 1
+	fi
+	return 0
+}
+
+
+use_current_release_branch_name() {
+	local current_branch=$(git_current_branch)
+	if startswith "$current_branch" "$PREFIX"; then
+		BRANCH=$current_branch
+		NAME=${BRANCH#$PREFIX}
+	else
+		warn "The current HEAD is no release branch."
+		warn "Please specify a <name> argument."
+		exit 1
+	fi
 }
diff --git a/git-sf-update b/git-sf-update
--- a/git-sf-update
+++ b/git-sf-update
@@ -41,12 +41,22 @@
 # policies, either expressed or implied, of Vincent Driessen.
 #
 
+require_git_repo
+require_springflow_initialized
+springflow_load_settings
+
 usage() {
-	echo "usage: git hf upgrade"
+	echo "usage: git sf update [-p]"
+}
+
+parse_args() {
+	# parse options
+	FLAGS "$@" || exit $?
+	eval set -- "${FLAGS_ARGV}"
 }
 
 cmd_default() {
-	cmd_upgrade "$@"
+	cmd_update "$@"
 }
 
 cmd_help() {
@@ -54,28 +64,36 @@ cmd_help() {
 	exit 0
 }
 
-cmd_upgrade() {
-	DEFINE_boolean check false "check for upgrade, but do not upgrade" c
-	# is there a new version available?
-	if ! hubflow_has_new_version_available > /dev/null ; then
-		die "You are already running the latest version"
-	elif flag check ; then
-		die "A newer version of the HubFlow tools is available"
+cmd_update() {
+	# flags
+	DEFINE_boolean prune true "delete local copies of branches that have been deleted from $ORIGIN" p
+	parse_args "$@"
+
+	# make sure we're okay to start
+	require_clean_working_tree
+
+	# fetch and merge the latest changes from origin
+	springflow_merge_latest_changes_from_origin
+
+	# make sure we end up where we should be
+	if [[ $(git_current_branch) != $BRANCH ]] ; then
+		git checkout "$BRANCH"
 	fi
 
-	# make sure there isn't already a gitflow folder here
-	if [ -e gitflow ] ; then
-		die "Cannot clone the HubFlow repo; there's already a folder called 'gitflow' in your current working directory"
+	# drop any branches that have disappeared from origin
+	if flag prune ; then
+		git fetch --prune || die "Unable to prune branches that no longer exist at '$ORIGIN'"
 	fi
 
-	git clone --recursive $HUBFLOW_REPO || die "Unable to clone the HubFlow repo"
-	cd hubflow || die "Could not find the gitflow repo we've just cloned"
-	./install.sh || die "Failed to install gitflow"
-	cd ..
-	rm -rf ./gitflow || die "Unable to remove the gitflow repo we've just cloned"
-
+	# all done
 	echo
 	echo "Summary of actions:"
-	echo "- A new version of the HubFlow tools has been installed"
-	echo
+	echo "- Any changes to branches at $ORIGIN have been downloaded to your local repository"
+	if flag prune ; then
+		echo "- Any branches that have been deleted at $ORIGIN have also been deleted from your local repository"
+	fi
+	echo "- Any changes from $ORIGIN/$MASTER_BRANCH have been merged into branch '$MASTER_BRANCH'"
+	echo "- Any changes from $ORIGIN/$DEVELOP_BRANCH have been merged into branch '$DEVELOP_BRANCH'"
+	echo "- Any resolved merge conflicts have been pushed back to $ORIGIN"
+	echo "- You are now on branch '$BRANCH'"
 }
diff --git a/git-sf-upgrade b/git-sf-upgrade
--- a/git-sf-upgrade
+++ b/git-sf-upgrade
@@ -11,7 +11,8 @@
 # Feel free to contribute to this project at:
 #    http://github.com/datasift/gitflow
 #
-# Copyright 2013 MediaSift Ltd. All rights reserved.
+# Copyright 2010 Vincent Driessen. All rights reserved.
+# Copyright 2012 MediaSift Ltd. All rights reserved.
 #
 #
 # Redistribution and use in source and binary forms, with or without
@@ -40,61 +41,41 @@
 # policies, either expressed or implied, of Vincent Driessen.
 #
 
-require_git_repo
-require_hubflow_initialized
-hubflow_load_settings
-
 usage() {
-    echo "usage: git hf push [-f]"
+	echo "usage: git sf upgrade"
 }
 
 cmd_default() {
-    cmd_push "$@"
+	cmd_upgrade "$@"
 }
 
 cmd_help() {
-    usage
-    exit 0
+	usage
+	exit 0
 }
 
-parse_args() {
-    # parse options
-    FLAGS "$@" || exit $?
-    eval set -- "${FLAGS_ARGV}"
-}
+cmd_upgrade() {
+	DEFINE_boolean check false "check for upgrade, but do not upgrade" c
+	# is there a new version available?
+	if ! springflow_has_new_version_available > /dev/null ; then
+		die "You are already running the latest version"
+	elif flag check ; then
+		die "A newer version of the HubFlow tools is available"
+	fi
 
-cmd_push() {
-    DEFINE_boolean force false "Forces a destructive push using the --force/-f flag" F
-    parse_args "$@"
+	# make sure there isn't already a gitflow folder here
+	if [ -e gitflow ] ; then
+		die "Cannot clone the HubFlow repo; there's already a folder called 'gitflow' in your current working directory"
+	fi
 
-    # make sure we're okay to start
-    require_clean_working_tree
+	git clone --recursive $SPRINGFLOW_REPO || die "Unable to clone the HubFlow repo"
+	cd springflow || die "Could not find the gitflow repo we've just cloned"
+	./install.sh || die "Failed to install gitflow"
+	cd ..
+	rm -rf ./springflow || die "Unable to remove the gitflow repo we've just cloned"
 
-    # fetch and merge the latest changes from origin
-    hubflow_fetch_latest_changes_from_origin
-    hubflow_remote_merge_helper "$ORIGIN" "$BRANCH"
-
-    # push to origin
-    if flag force ; then
-        hubflow_push_latest_changes_to_origin force
-    else
-        hubflow_push_latest_changes_to_origin
-    fi
-    local result=$?
-
-    # what happened?
-    echo
-    echo "Summary of actions:"
-    if [[ $result -eq 1 ]] ; then
-        echo "- A new remote branch '$ORIGIN/$BRANCH' was created"
-        echo "- The local branch '$BRANCH' was configured to track the remote branch"
-    elif [[ $result -eq 2 ]] ; then
-        echo "- The remote branch '$ORIGIN/$BRANCH' was overwritten with your changes"
-    elif [[ $result -eq 3 ]] ; then
-        echo "- The remote branch '$ORIGIN/$BRANCH' was updated with your changes"
-    else
-        echo "- No action taken, '$ORIGIN/$BRANCH' already up-to-date"
-    fi
-
-    # all done
+	echo
+	echo "Summary of actions:"
+	echo "- A new version of the HubFlow tools has been installed"
+	echo
 }
